#Requires AutoHotkey v2.0

/**
 * @file _YamlTokenQueue.ahk
 * @description YAML Token Queue.
 * @author nullmake
 * @license Apache-2.0
 * Copyright 2026 nullmake
 */

/**
 * Queue for managing tokens generated by the LayoutProcessor.
 */
class _YamlTokenQueue {
    /** @field {_YamlTracer|String} _tracer - Scoped tracer instance */
    _tracer := ""

    /** @field {Array} _tokenQueue - Internal array holding tokens */
    _tokenQueue := []

    /**
     * @param {_YamlTracer|String} [tracer=""] - Scoped tracer instance
     */
    __New(tracer := "") {
        this._tracer := tracer
    }

    /**
     * Creates a deep copy of the queue.
     * @returns {Object} Cloned queue
     */
    Clone() {
        clone := _YamlTokenQueue(this._tracer)
        clone._tokenQueue := this._tokenQueue.Clone()
        return clone
    }

    /**
     * Current number of tokens in the queue.
     */
    Length => this._tokenQueue.Length

    /**
     * Pushes a token to the end of the queue.
     * @param {Object} token
     */
    Push(token) {
        if (this._tracer) {
            this._tracer.Trace("TOKEN_PUSH: " . token.ToString())
        }
        this._tokenQueue.Push(token)
    }

    /**
     * Removes and returns the first token from the queue.
     * @returns {Object}
     */
    Pop() {
        token := this._tokenQueue.RemoveAt(1)
        if (this._tracer) {
            this._tracer.Trace("TOKEN_POP: " . token.ToString())
        }
        return token
    }

    /**
     * Returns the token at the specified index without removing it.
     * @param {Integer} [index=1]
     * @returns {Object}
     */
    Peek(index := 1) {
        return this._tokenQueue[index]
    }

    /**
     * Gets or sets the token at the specified index.
     * @param {Integer} Index
     */
    __Item[Index] {
        get => this._tokenQueue[Index]
        set => this._tokenQueue[Index]
    }
}
